const bookList = [
  {
    name: "Crime And Punishment",
    author: "Fyodor Dostoevsky",
    year: 1866,
    description:
      "Raskolnikov, a destitute and desperate former student, wanders through the slums of St Petersburg and commits a random murder without remorse or regret.",
    price: 6.5,
    categories: ["Novel", "Fiction", "Crime Fiction"],
    stock: 10,
    imageUrl: "/books/crime-and-punishment.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Random House",
      "May 06, 2003 | 384 Pages | 5-7/16 x 8",
      "ISBN 9780452284234",
    ],
  },
  {
    name: "1984",
    author: "George Orwell",
    year: 1949,
    description:
      "Nineteen Eighty-Four, a dystopian novel by George Orwell that was published in 1949 is a cautionary tale about the consequences of allowing a government to have complete control.",
    price: 6.75,
    categories: ["Novel", "Fiction", "Science Fiction"],
    stock: 10,
    imageUrl: "/books/1984.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Random House",
      "May 06, 2003 | 284 Pages | 5-7/16 x 8",
      "ISBN 9780452284234",
    ],
  },
  {
    name: "Animal Farm",
    author: "George Orwell",
    year: 1945,
    description:
      "Animal Farm is a beast fable that tells the story of a group of anthropomorphic farm animals who rebel against their human farmer, hoping to create a society where the animals can be equal, free, and happy.",
    price: 6.8,
    categories: ["Novella", "Fiction", "Satire"],
    stock: 9,
    imageUrl: "/books/animal-farm.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Random House",
      "May 06, 2003 | 193 Pages | 5-7/16 x 8",
      "ISBN 9780452284234",
    ],
  },
  {
    name: "Lord Of The Flies",
    author: "William Golding",
    year: 1954,
    description:
      "Lord of the Flies is the story of a group of British boys who are stranded on an uninhabited island and their disastrous attempts to govern themselves.",
    price: 7,
    categories: ["Novel", "Fiction"],
    stock: 10,
    imageUrl: "/books/lord-of-the-flies.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Random House",
      "May 06, 2003 | 384 Pages | 5-7/16 x 8",
      "ISBN 9780452284234",
    ],
  },
  {
    name: "The Haunting Of Hill House",
    author: "Shirley Jackson",
    year: 1959,
    description:
      "The Haunting Of Hill House is the story of four seekers who arrive at a notoriously unfriendly pile called Hill House: Dr. Montague, an occult scholar looking for solid evidence of a 'haunting'.",
    price: 7,
    categories: ["Novel", "Fiction", "Horror"],
    stock: 10,
    imageUrl: "/books/the-haunting-of-hill-house.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Random House",
      "May 06, 2003 | 384 Pages | 5-7/16 x 8",
      "ISBN 9780452284234",
    ],
  },
  {
    name: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    year: 1880,
    description:
      "The Brothers Karamazov is a novel by Fyodor Dostoevsky that explores complex themes of spirituality, morality, and the nature of existence through the story of the Karamazov family.",
    price: 7.5,
    categories: ["Novel", "Fiction", "Philosophical"],
    stock: 10,
    imageUrl: "/books/the-brothers-karamazov.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Random House",
      "May 06, 2003 | 800 Pages | 5-7/16 x 8",
      "ISBN 9780452284234",
    ],
  },
  {
    name: "Pride and Prejudice",
    author: "Jane Austen",
    year: 1813,
    description:
      "Pride and Prejudice follows the lives of the Bennett family and their romantic endeavors in 19th-century England.",
    price: 8.5,
    categories: ["Novel", "Romance"],
    stock: 15,
    imageUrl: "/books/pride-and-prejudice.jpeg",
    details: [
      "Paperback",
      "Published by Vintage Books",
      "January 30, 2007 | 320 Pages | 5-1/5 x 8",
      "ISBN 9780307386864",
    ],
  },
  {
    name: "To Kill a Mockingbird",
    author: "Harper Lee",
    year: 1960,
    description:
      "To Kill a Mockingbird is a novel set in the American South during the 1930s and deals with issues of racial injustice and moral growth.",
    price: 9.25,
    categories: ["Novel", "Fiction", "Legal Drama"],
    stock: 12,
    imageUrl: "/books/to-kill-a-mockingbird.jpeg",
    details: [
      "Paperback",
      "Published by Harper Perennial Modern Classics",
      "October 11, 2005 | 336 Pages | 5-1/4 x 8",
      "ISBN 9780061120084",
    ],
  },
  {
    name: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    year: 1925,
    description:
      "The Great Gatsby is a novel set in the Jazz Age and follows the lives of wealthy New Yorkers as they navigate love, wealth, and societal expectations.",
    price: 10.75,
    categories: ["Novel", "Fiction", "Classic"],
    stock: 8,
    imageUrl: "/books/the-great-gatsby.jpeg",
    details: [
      "Paperback",
      "Published by Scribner",
      "September 30, 2004 | 180 Pages | 5-1/2 x 8-1/2",
      "ISBN 9780743273565",
    ],
  },
  {
    name: "Moby-Dick",
    author: "Herman Melville",
    year: 1851,
    description:
      "Moby-Dick is a novel about the voyage of the whaling ship Pequod, captained by the obsessed and monomaniacal Captain Ahab, who seeks revenge on the white whale Moby Dick.",
    price: 11,
    categories: ["Novel", "Adventure"],
    stock: 9,
    imageUrl: "/books/moby-dick.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Classics",
      "March 28, 2003 | 624 Pages | 5-1/16 x 7-3/4",
      "ISBN 9780142437247",
    ],
  },
  {
    name: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    year: 1865,
    description:
      "Alice's Adventures in Wonderland is a fantasy novel about a young girl named Alice who falls through a rabbit hole into a bizarre world full of peculiar creatures and nonsensical situations.",
    price: 8,
    categories: ["Novel", "Fantasy"],
    stock: 11,
    imageUrl: "/books/alices-adventures-in-wonderland.jpeg",
    details: [
      "Paperback",
      "Published by Puffin Books",
      "June 30, 1992 | 192 Pages | 5-1/16 x 7-3/4",
      "ISBN 9780141439761",
    ],
  },
  {
    name: "Wuthering Heights",
    author: "Emily Brontë",
    year: 1847,
    description:
      "Wuthering Heights is a novel that explores the passionate and destructive love between Catherine Earnshaw and Heathcliff, set against the backdrop of the Yorkshire moors.",
    price: 7.75,
    categories: ["Novel", "Gothic Fiction", "Romance"],
    stock: 10,
    imageUrl: "/books/wuthering-heights.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Classics",
      "January 30, 2003 | 416 Pages | 5-1/16 x 7-3/4",
      "ISBN 9780141439556",
    ],
  },
  {
    name: "The Catcher in the Rye",
    author: "J.D. Salinger",
    year: 1951,
    description:
      "The Catcher in the Rye is a novel narrated by Holden Caulfield, a teenage boy who reflects on his experiences in New York City after being expelled from prep school.",
    price: 8.25,
    categories: ["Novel", "Fiction", "Coming-of-Age"],
    stock: 11,
    imageUrl: "/books/the-catcher-in-the-rye.jpeg",
    details: [
      "Paperback",
      "Published by Little, Brown and Company",
      "May 01, 1991 | 288 Pages | 5-1/4 x 8",
      "ISBN 9780316769174",
    ],
  },
  {
    name: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    year: 1890,
    description:
      "The Picture of Dorian Gray is a novel about a young man, Dorian Gray, who sells his soul in exchange for eternal youth, leading to a life of decadence and moral corruption.",
    price: 7.5,
    categories: ["Novel", "Gothic Fiction", "Philosophical"],
    stock: 10,
    imageUrl: "/books/the-picture-of-dorian-gray.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Classics",
      "June 05, 2003 | 304 Pages | 5-1/16 x 7-3/4",
      "ISBN 9780141439570",
    ],
  },
  {
    name: "Jane Eyre",
    author: "Charlotte Brontë",
    year: 1847,
    description:
      "Jane Eyre is a novel that follows the experiences of its eponymous character, from her abusive childhood to her blossoming love for Mr. Rochester.",
    price: 7.25,
    categories: ["Novel", "Gothic Fiction", "Romance"],
    stock: 9,
    imageUrl: "/books/jane-eyre.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Classics",
      "April 29, 2003 | 624 Pages | 5-1/16 x 7-3/4",
      "ISBN 9780141439518",
    ],
  },
  {
    name: "Frankenstein",
    author: "Mary Shelley",
    year: 1818,
    description:
      "Frankenstein is a novel about Victor Frankenstein, a scientist who creates a grotesque creature in an unorthodox scientific experiment, leading to tragic consequences.",
    price: 7,
    categories: ["Novel", "Gothic Fiction", "Science Fiction"],
    stock: 10,
    imageUrl: "/books/frankenstein.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Classics",
      "October 31, 2013 | 288 Pages | 5-1/16 x 7-3/4",
      "ISBN 9780141439471",
    ],
  },
  {
    name: "Dracula",
    author: "Bram Stoker",
    year: 1897,
    description:
      "Dracula is a gothic horror novel about Count Dracula's attempt to move from Transylvania to England so he may find new blood and spread the undead curse.",
    price: 7.5,
    categories: ["Novel", "Gothic Fiction", "Horror"],
    stock: 11,
    imageUrl: "/books/dracula.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Classics",
      "December 31, 2002 | 512 Pages | 5-1/16 x 7-3/4",
      "ISBN 9780141439846",
    ],
  },
  {
    name: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    year: 1979,
    description:
      "The Hitchhiker's Guide to the Galaxy is a humorous science fiction series following the adventures of Arthur Dent after Earth's destruction.",
    price: 9,
    categories: ["Novel", "Science Fiction", "Humor"],
    stock: 10,
    imageUrl: "/books/hitchhikers-guide-to-the-galaxy.jpeg",
    details: [
      "Paperback",
      "Published by Del Rey Books",
      "September 27, 1995 | 224 Pages | 5-1/2 x 8-1/4",
      "ISBN 9780345391803",
    ],
  },
  {
    name: "The Adventures of Huckleberry Finn",
    author: "Mark Twain",
    year: 1884,
    description:
      "The Adventures of Huckleberry Finn follows the escapades of a young boy and a runaway slave as they travel down the Mississippi River on a raft, facing various challenges and learning about life along the way.",
    price: 7.25,
    categories: ["Novel", "Adventure", "Satire"],
    stock: 9,
    imageUrl: "/books/the-adventures-of-huckleberry-finn.jpeg",
    details: [
      "Paperback",
      "Published by Dover Publications",
      "April 19, 1994 | 224 Pages | 5-3/16 x 8-1/4",
      "ISBN 9780486280615",
    ],
  },
  {
    name: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    year: 1952,
    description:
      "The Old Man and the Sea is a short novel about an aging fisherman named Santiago who struggles with a giant marlin far out in the Gulf Stream off the coast of Cuba.",
    price: 7.5,
    categories: ["Novella", "Fiction"],
    stock: 10,
    imageUrl: "/books/the-old-man-and-the-sea.jpeg",
    details: [
      "Paperback",
      "Published by Scribner",
      "May 05, 1995 | 128 Pages | 5-1/2 x 8-1/4",
      "ISBN 9780684801223",
    ],
  },
  {
    name: "The Sun Also Rises",
    author: "Ernest Hemingway",
    year: 1926,
    description:
      "The Sun Also Rises is a novel that portrays the lives of expatriates in post-World War I Europe, focusing on the experiences of a group of American and British expatriates in Paris and Spain.",
    price: 8,
    categories: ["Novel", "Fiction"],
    stock: 11,
    imageUrl: "/books/the-sun-also-rises.jpeg",
    details: [
      "Paperback",
      "Published by Scribner",
      "September 02, 2014 | 256 Pages | 5-1/2 x 8-1/4",
      "ISBN 9781501121968",
    ],
  },
  {
    name: "The Grapes of Wrath",
    author: "John Steinbeck",
    year: 1939,
    description:
      "The Grapes of Wrath is a novel set during the Great Depression and follows the Joad family as they migrate from Oklahoma to California in search of work, depicting the hardships faced by migrant workers.",
    price: 8.25,
    categories: ["Novel", "Fiction"],
    stock: 10,
    imageUrl: "/books/the-grapes-of-wrath.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Classics",
      "March 28, 2006 | 544 Pages | 5-1/16 x 7-3/4",
      "ISBN 9780143039433",
    ],
  },
  {
    name: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    year: 1967,
    description:
      "One Hundred Years of Solitude is a landmark novel that tells the multi-generational story of the Buendía family in the fictional town of Macondo, blending magical realism with historical events.",
    price: 9,
    categories: ["Novel", "Fiction"],
    stock: 9,
    imageUrl: "/books/one-hundred-years-of-solitude.jpeg",
    details: [
      "Paperback",
      "Published by Harper Perennial Modern Classics",
      "February 21, 2006 | 417 Pages | 5-5/16 x 8",
      "ISBN 9780060883287",
    ],
  },
  {
    name: "The Adventures of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    year: 1892,
    description:
      "The Adventures of Sherlock Holmes is a collection of twelve short stories featuring Sherlock Holmes, a famous detective known for his logical reasoning and keen observation skills.",
    price: 8,
    categories: ["Short Stories", "Mystery"],
    stock: 10,
    imageUrl: "/books/the-adventures-of-sherlock-holmes.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Classics",
      "June 06, 2001 | 256 Pages | 5-1/16 x 7-3/4",
      "ISBN 9780140439077",
    ],
  },
  {
    name: "The Hound of the Baskervilles",
    author: "Arthur Conan Doyle",
    year: 1902,
    description:
      "The Hound of the Baskervilles is a detective novel where Sherlock Holmes and Dr. Watson investigate the mysterious death of Sir Charles Baskerville and the legend of a supernatural hound haunting the Baskerville family.",
    price: 7.5,
    categories: ["Novel", "Mystery"],
    stock: 9,
    imageUrl: "/books/the-hound-of-the-baskervilles.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Classics",
      "April 29, 2003 | 240 Pages | 5-1/16 x 7-3/4",
      "ISBN 9780141439334",
    ],
  },
  {
    name: "A Study in Scarlet",
    author: "Arthur Conan Doyle",
    year: 1887,
    description:
      "A Study in Scarlet is the first novel to feature Sherlock Holmes and Dr. Watson. It follows their investigation into a murder in London and introduces readers to the iconic detective duo.",
    price: 7,
    categories: ["Novel", "Mystery"],
    stock: 10,
    imageUrl: "/books/a-study-in-scarlet.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Classics",
      "October 31, 2001 | 192 Pages | 5-1/16 x 7-3/4",
      "ISBN 9780140439084",
    ],
  },
  {
    name: "The Sign of the Four",
    author: "Arthur Conan Doyle",
    year: 1890,
    description:
      "The Sign of the Four is a novel where Sherlock Holmes and Dr. Watson solve a complex case involving stolen treasure, secret pacts, and murder.",
    price: 7.25,
    categories: ["Novel", "Mystery"],
    stock: 8,
    imageUrl: "/books/the-sign-of-the-four.jpeg",
    details: [
      "Paperback",
      "Published by Penguin Classics",
      "July 31, 2001 | 160 Pages | 5-1/16 x 7-3/4",
      "ISBN 9780140439077",
    ],
  },
];

export default bookList;
